version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_DATABASE=test
    networks:
      - go-gc-community

volumes:
  mysql_data:
    name: mysql_data
